import BackgroundContent from './image/background.jpg'
import ICcall from './icon/call.png'
import ICcart from './icon/cart.png'
import ICemail from './icon/email.png'
import ICfacebook from './icon/facebook.png'
import ICinstagram from './icon/instagram.png'
import ICtwitter from './icon/twitter.png'
import ICyoutube from './icon/youtube.png'
import logoBK from './image/logoBK.png'
import Listmenu1 from'./image/listmenu1.jpg'
import Listmenu2 from'./image/listmenu2.jpg'
import Listmenu3 from'./image/listmenu3.jpg'
import Listmenu4 from'./image/listmenu4.jpg'
import Listmenu5 from'./image/listmenu5.jpg'
import Listmenu6 from'./image/listmenu6.jpg'
import Listmenu7 from'./image/listmenu7.jpg'
import Listmenu8 from'./image/listmenu8.jpg'
import Listmenu9 from'./image/listmenu9.jpg'
import ImgRegis from './image/regis.png'

export {ImgRegis, Listmenu1, Listmenu2, Listmenu3, Listmenu4, Listmenu5, Listmenu6, Listmenu7, Listmenu8, Listmenu9, BackgroundContent, ICcall, ICcart, ICemail, ICfacebook, ICinstagram, ICtwitter, ICyoutube, logoBK};